import React from 'react';
import Head from 'next/head';
const Layout = ({title,children}) => {
    return (
        <div className='bg-gray-300'>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='container mx-auto  pt-8 pb-14 max-w-4xl min-h-screen'>
                {children}
            </main>

        </div>
    );
};

export default Layout;